name = "ImmutableVectors"
uuid = "d6059b30-97e8-4ff2-b426-20b29c0469af"
authors = ["Felipe A. V. de Bragança Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
